language: go

matrix:
  include:
    - name: "Test MySql:5.7"
      go: 1.12.x
      services:
        - mysql
      env:
        - PLATFORM=mysql:5.7
        - SERVER_NAME=127.0.0.1
        - DB_NAME=workspace
        - DB_USER=root
      before_install:
        - go get -v github.com/go-sql-driver/mysql
        - mysql -e 'CREATE DATABASE workspace;'

    - name: "Test MySql"
      go: 1.12.x
      services:
        - mysql
      before_script:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
      env:
        - PLATFORM=mysql:8.0
        - SERVER_NAME=127.0.0.1
        - DB_NAME=workspace
        - DB_USER=root
      before_install:
        - go get -v github.com/go-sql-driver/mysql
        - mysql -e 'CREATE DATABASE workspace;'

    - name: "Test PostgresSQL"
      go: 1.12.x
      services:
        - postgresql
      env:
        - PLATFORM=postgres
        - SERVER_NAME=127.0.0.1
        - DB_NAME=workspace
        - DB_USER=postgres
      before_install:
        - go get -v github.com/lib/pq
        - psql -c 'create database workspace;' -U postgres

    - name: "Test SQLite"
      go: 1.12.x
      env:
        - PLATFORM=sqlite3
      before_install:
        - go get -v github.com/mattn/go-sqlite3

    - name: "Test MsSQL"
      go: 1.12.x
      services:
        - docker
      env:
        - PLATFORM=sqlserver
        - SERVER_NAME=127.0.0.1
        - DB_NAME=master
        - DB_USER=sa
        - DB_PASSWORD=TheStrong!Passw0rd
      before_script:
        - sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=TheStrong!Passw0rd' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest
      before_install:
        - go get -v github.com/denisenkom/go-mssqldb

script:
  - go test ./...
