language: go

services:
  - mysql

go:
  - 1.12.x

before_install:
  - go get -v github.com/go-sql-driver/mysql
  - go get -v github.com/mattn/go-sqlite3
  - mysql -e 'CREATE DATABASE workspace;'

jobs:
  include:
    - stage: test
      script: ENV=CI DRIVER=mysql go test ./...
    - script: ENV=CI DRIVER=sqlite3 go test ./...
